### PR TITLE
Four pair

### PR DESCRIPTION
**Pull request by txtincorporated**

### CODE REVIEW

**Comment by newcomercurt** [comment]
I worked with Nathan, Aaron, and Charles. It took us about 2.5 hours to get this lab done. I really felt like I understood  handlebars much better after doing this and I was able to apply my knowledge to this lab. The hardest part was the extra credit part, I wouldn't change anything about this lab.

**Comment by CharlesEmrich** [comment]
Who you worked with: Nathan, Curt, Aaron
How long it took you to complete this lab: about 2.5 hrs
What technical aspect you found most enjoyable/interesting: Probably structuring the function call on the compiled template in the EC section of the assignment. Also, coincidentally, the hardest part. Usually those aren't the same thing. But the existing version of the thing is kind of a masterpiece of chaining and I'm proud of it.
What aspects (non-technical or technical) that you found most challenging: As above.
What aspect(s) of this lab could be improved: Kinda think the EC could be worth more? It was about 60% of the labor of the lab and will account for 10% of the points.

**Comment by txtincorporated** [comment]
https://github.com/txtincorporated/day4_blog_lab/pull/1

In your PR comment, include these items:

Who you worked with
Aaron, Charles and Curt

How long it took you to complete this lab
2.5 hrs.

What technical aspect you found most enjoyable/interesting
Definitely trying to extend the HB templating to dual contexts simultaneously.

What aspects (non-technical or technical) that you found most challenging
Ditto above.  It would have been cool to do both filters in one template.

What aspect(s) of this lab could be improved
That would be hard to say.  There were no real frustrations here, possibly because we had a lot of brains on it at once.

**Comment by aaronbini** [comment]
I worked with Nathan, Curt, and Charles on this. Working with the templating was really interesting and I enjoyed that. The extra credit was definitely a challenge. I'm starting to see the real value in templating and hope I can continue to learn to implement templating in my projects. I don't think you need to change anything about the lab.

**Pull request merged**
